#include-once

#Region Arrays
#Region Agent
Global $mAgentvtable[2] = ['ptr', 0]
Global $mAgentTimer[2] = ['long', 20]
Global $mAgentNearestAgentPtr[2] = ['ptr', 28]
Global $mAgentNextAgent[2] = ['ptr', 32]
Global $mAgentId[2] = ['long', 44]
Global $mAgentZ[2] = ['float', 48]
Global $mAgentBoxHoverWidth[2] = ['float', 60]
Global $mAgentBoxHoverHeight[2] = ['float', 64]
Global $mAgentRotation[2] = ['float', 76]
Global $mAgentNameProperties[2] = ['long', 88]
Global $mAgentX[2] = ['float', 116]
Global $mAgentY[2] = ['float', 120]
Global $mAgentGround[2] = ['long', 124]
Global $mAgentNameTagX[2] = ['float', 132]
Global $mAgentNameTagY[2] = ['float', 136]
Global $mAgentNameTagZ[2] = ['float', 140]
Global $mAgentType[2] = ['long', 156]
Global $mAgentMoveX[2] = ['float', 160]
Global $mAgentMoveY[2] = ['float', 164]
Global $mAgentOwner[2] = ['long', 196]
Global $mAgentExtraType[2] = ['long', 208]
Global $mAgentAnimation[2] = ['byte', 220]
Global $mAgentAttackSpeed[2] = ['float', 236]
Global $mAgentAttackSpeedModifier[2] = ['float', 240]
Global $mAgentPlayerNumber[2] = ['word', 244]
Global $mAgentPlayerOrNPC[2] = ['char', 247]
Global $mAgentEquip[2] = ['ptr', 252]
Global $mAgentPrimary[2] = ['byte', 266]
Global $mAgentSecondary[2] = ['byte', 267]
Global $mAgentLevel[2] = ['byte', 268]
Global $mAgentTeam[2] = ['byte', 269]
Global $mAgentEnergyPips[2] = ['float', 276]
Global $mAgentEnergyPercent[2] = ['float', 284]
Global $mAgentMaxEnergy[2] = ['long', 288]
Global $mAgentHPPips[2] = ['float', 296]
Global $mAgentHP[2] = ['float', 304]
Global $mAgentMaxHP[2] = ['long', 308]
Global $mAgentEffects[2] = ['long', 312]
Global $mAgentHex[2] = ['byte', 320]
Global $mAgentModelState[2] = ['long', 340]
Global $mAgentTypeMap[2] = ['long', 344]
Global $mAgentInSpiritRange[2] = ['long', 364]
Global $mAgentLoginNumber[2] = ['long', 384]
Global $mAgentModelMode[2] = ['float', 388]
Global $mAgentModelAnimation[2] = ['long', 396]
Global $mAgentLastStrike[2] = ['byte', 432]
Global $mAgentAllegiance[2] = ['byte', 433]
Global $mAgentWeaponType[2] = ['word', 434]
Global $mAgentSkill[2] = ['word', 436]
Global $mAgentWeaponItemId[2] = ['word', 442]
Global $mAgentOffhandItemId[2] = ['word', 444]
#EndRegion

#Region Bag
Global $mBagType[2] = ['long', 0]
Global $mBagIndex[2] = ['long', 4]
Global $mBagId[2] = ['long', 8]
Global $mBagContainerItem[2] = ['ptr', 12]
Global $mBagItemsCount[2] = ['long', 16]
Global $mBagArray[2] = ['ptr', 20]
Global $mBagItemArray[2] = ['ptr', 24]
Global $mBagFakeSlots[2] = ['long', 28]
Global $mBagSlots[2] = ['long', 32]
#EndRegion

#Region Buff
Global $mBuffSkillId[2] = ['long', 0]
Global $mBuffId[2] = ['long', 8]
Global $mBuffTargetId[2] = ['long', 12]
#EndRegion

#Region Item
Global $mItemId[2] = ['long', 0]
Global $mItemAgentId[2] = ['long', 4]
Global $mItemBag[2] = ['ptr', 12]
Global $mItemModstruct[2] = ['ptr', 16]
Global $mItemModstructsize[2] = ['long', 20]
Global $mItemCustomized[2] = ['ptr', 24]
Global $mItemType[2] = ['byte', 32]
Global $mItemExtraId[2] = ['short', 34]
Global $mItemValue[2] = ['short', 36]
Global $mItemInteraction[2] = ['short', 40]
Global $mItemModelId[2] = ['long', 44]
Global $mItemModString[2] = ['ptr', 48]
Global $mItemNameString[2] = ['ptr', 56]
Global $mItemQuantity[2] = ['byte', 75]
Global $mItemEquipped[2] = ['byte', 76]
Global $mItemSlot[2] = ['byte', 78]
#EndRegion

#Region Quest
Global $mQuestId[2] = ['long', 0]
Global $mQuestLogState[2] = ['long', 4]
Global $mQuestMapFrom[2] = ['long', 20]
Global $mQuestX[2] = ['float', 24]
Global $mQuestY[2] = ['float', 28]
Global $mQuestMapTo[2] = ['long', 40]
#EndRegion

#Region Skillbar
Global $mSbarAgentId[2] = ['long', 0]
Global $mSbarAdrenalineA1[2] = ['long', 4]
Global $mSbarAdrenalineB1[2] = ['long', 8]
Global $mSbarRecharge1[2] = ['dword', 12]
Global $mSbarId1[2] = ['dword', 16]
Global $mSbarEvent1[2] = ['dword', 20]
Global $mSbarAdrenalineA2[2] = ['long', 24]
Global $mSbarAdrenalineB2[2] = ['long', 28]
Global $mSbarRecharge2[2] = ['dword', 32]
Global $mSbarId2[2] = ['dword', 36]
Global $mSbarEvent2[2] = ['dword', 40]
Global $mSbarAdrenalineA3[2] = ['long', 44]
Global $mSbarAdrenalineB3[2] = ['long', 48]
Global $mSbarRecharge3[2] = ['dword', 52]
Global $mSbarId3[2] = ['dword', 56]
Global $mSbarEvent3[2] = ['dword', 60]
Global $mSbarAdrenalineA4[2] = ['long', 64]
Global $mSbarAdrenalineB4[2] = ['long', 68]
Global $mSbarRecharge4[2] = ['dword', 72]
Global $mSbarId4[2] = ['dword', 76]
Global $mSbarEvent4[2] = ['dword', 80]
Global $mSbarAdrenalineA5[2] = ['long', 84]
Global $mSbarAdrenalineB5[2] = ['long', 88]
Global $mSbarRecharge5[2] = ['dword', 92]
Global $mSbarId5[2] = ['dword', 96]
Global $mSbarEvent5[2] = ['dword', 100]
Global $mSbarAdrenalineA6[2] = ['long', 104]
Global $mSbarAdrenalineB6[2] = ['long', 108]
Global $mSbarRecharge6[2] = ['dword', 112]
Global $mSbarId6[2] = ['dword', 116]
Global $mSbarEvent6[2] = ['dword', 120]
Global $mSbarAdrenalineA7[2] = ['long', 124]
Global $mSbarAdrenalineB7[2] = ['long', 128]
Global $mSbarRecharge7[2] = ['dword', 132]
Global $mSbarId7[2] = ['dword', 136]
Global $mSbarEvent7[2] = ['dword', 140]
Global $mSbarAdrenalineA8[2] = ['long', 144]
Global $mSbarAdrenalineB8[2] = ['long', 148]
Global $mSbarRecharge8[2] = ['dword', 152]
Global $mSbarId8[2] = ['dword', 156]
Global $mSbarEvent8[2] = ['dword', 160]
Global $mSbarDisabled[2] = ['dword', 164]
Global $mSbarCasting[2] = ['dword', 176]
#EndRegion

#Region SkillEffect
Global $mEffectSkillId[2] = ['long', 0]
Global $mEffectType[2] = ['long', 4]
Global $mEffectId[2] = ['long', 8]
Global $mEffectAgentId[2] = ['long', 12]
Global $mEffectDuration[2] = ['float', 16]
Global $mEffectTimeStamp[2] = ['long', 20]
#EndRegion

#Region Skill
Global $mSkillID[2] = ['long', 0]
Global $mSkillCampaign[2] = ['long', 8]
Global $mSkillType[2] = ['long', 12]
Global $mSkillSpecial[2] = ['long', 16]
Global $mSkillComboReq[2] = ['long', 20]
Global $mSkillEffect1[2] = ['long', 24]
Global $mSkillCondition[2] = ['long', 28]
Global $mSkillEffect2[2] = ['long', 32]
Global $mSkillWeaponReq[2] = ['long', 36]
Global $mSkillProfession[2] = ['byte', 40]
Global $mSkillAttribute[2] = ['byte', 41]
Global $mSkillPvPID[2] = ['long', 44]
Global $mSkillCombo[2] = ['byte', 48]
Global $mSkillTarget[2] = ['byte', 49]
Global $mSkillEquipType[2] = ['byte', 51]
Global $mSkillEnergyCost[2] = ['byte', 53]
Global $mSkillHealthCost[2] = ['byte', 54]
Global $mSkillAdrenaline[2] = ['dword', 56]
Global $mSkillActivation[2] = ['float', 60]
Global $mSkillAftercast[2] = ['float', 64]
Global $mSkillDuration0[2] = ['long', 68]
Global $mSkillDuration15[2] = ['long', 72]
Global $mSkillRecharge[2] = ['long', 76]
Global $mSkillScale0[2] = ['long', 92]
Global $mSkillScale15[2] = ['long', 96]
Global $mSkillBonusScale0[2] = ['long', 100]
Global $mSkillBonusScale15[2] = ['long', 104]
Global $mSkillAoERange[2] = ['float', 108]
Global $mSkillConstEffect[2] = ['float', 112]
#EndRegion
#EndRegion

#Region GetValue
;~ Description: Easier format of memreads.
;~ Example: Skill ID ->
;~    $lSkillID = GetMemoryValue($lSkillPtr, $mSkillID)
Func GetMemoryValue($aPtr, $aGlobalArray)
   Return MemoryRead($aPtr + $aGlobalArray[1], $aGlobalArray[0])
EndFunc   ;==>GetMemoryValue
#EndRegion